### ISSUE TITLE
ArgumentException in AttributeMetadataModule.AttachToComponentRegistration

### ISSUE THREAD

**Issue by BigApple1988** [autofac/Autofac.Extras.AttributeMetadata#4]
I have an ArgumentException while creating nested lifetimeScope from AttributeMetadataModule.AttachToComponentRegistration. It happened because in this method adds entries in Metadata dictionary.
Source of issue https://github.com/autofac/Autofac/commit/b65821a221b63b55404b95f63fac188769b4dcda

**Comment by BigApple1988** [comment]
https://github.com/autofac/Autofac.Extras.AttributeMetadata/pull/3

**Comment by tillig** [comment]
Fix for this is released as 4.0.2.
