### ISSUE TITLE
Finish SourceLink integration

### ISSUE THREAD

**Issue by tillig** [autofac/Autofac.Extras.AttributeMetadata#5]
I started SourceLink integration in this library by adding the Microsoft SourceLink package into the main project but on building the package I don't see the SourceLink info in the final .nupkg. Obviously something more needs to be done to support this; I'm not sure exactly what off the top of my head.

**Comment by alexmg** [comment]
I've updated this package to .NET Standard 2.0 and can see the entry below in the generated `.nuspec` file.

```
<repository type="git" url="https://github.com/autofac/Autofac.Extras.AttributeMetadata" commit="55583e4fa74bc357b53cbbcb1d30a8a67c54cd54" />
```

Is that all that is required?

**Comment by tillig** [comment]
I think that's all that was missing. Could be that it didn't work in full framework projects at the time.

Glad you were able to get MEF working. When I looked at it a while back there were some incompatibilities, like not all the types we needed were included in the System.ComponentModel.Composition library.
